// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMSkAmvOktwNIOUG_nNcMkSqLSvCrOJag',
    appId: '1:1026039172312:web:dc4699e40e23c92ccd5bad',
    messagingSenderId: '1026039172312',
    projectId: 'cyphlabs-expense-tracker',
    authDomain: 'cyphlabs-expense-tracker.firebaseapp.com',
    storageBucket: 'cyphlabs-expense-tracker.firebasestorage.app',
    measurementId: 'G-VBV356M4VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzLQMcgfWNYm_2u2aSSL5BgHFmGTGW14',
    appId: '1:1026039172312:android:f427cb65dad9cec9cd5bad',
    messagingSenderId: '1026039172312',
    projectId: 'cyphlabs-expense-tracker',
    storageBucket: 'cyphlabs-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMSkAmvOktwNIOUG_nNcMkSqLSvCrOJag',
    appId: '1:1026039172312:web:611cac56e7d2b0b7cd5bad',
    messagingSenderId: '1026039172312',
    projectId: 'cyphlabs-expense-tracker',
    authDomain: 'cyphlabs-expense-tracker.firebaseapp.com',
    storageBucket: 'cyphlabs-expense-tracker.firebasestorage.app',
    measurementId: 'G-T1E3R2WCEM',
  );
}
